Feat/translations
sousandrei/ledger-bot pull request #19
Opened 2021-04-20 07:17 UTC by Canato

Ta certo isso ai ou tem jeito melhor de fazer?

2021-04-20 10:06 UTC, sousandrei requested changes
Boto fe que a gente pode separar traducao por modulo e so compila o bot com a linguagem certa. Dessa forma da pra ter o mesmo formato de arquivo.
Pra isso tem que declarar features e so chamar o certo
```rust
#[cfg(feature = "pt")]
mod pt;

#[cfg(feature = "pt")]
use pt::Traducoes


#[cfg(feature = "pt")]
mod en;

#[cfg(feature = "pt")]
use en::Traducoes
```
Referencia: 
https://doc.rust-lang.org/cargo/reference/features.html

2021-04-20 10:06 UTC, sousandrei commented on src/bot.rs
> +#[path = "translations/str.rs"] mod str;
Isso nao significa nada no rust :/ 
o `#[command]` eh uma macro em tempo de compilacao da lib do telegram
usa so o mod mesmo

2021-04-20 10:06 UTC, sousandrei commented on src/bot.rs
> +    #[command(description = str::help())]
Nao sei se ele aceita funcao porque eh em tempo de compile

2021-04-20 10:06 UTC, sousandrei commented on src/translations/str.rs
> +const lan: String = Language::BR;
Seria tipo `Language`

2021-04-20 10:06 UTC, sousandrei commented on src/translations/str.rs
> +fn intro() -> String {
Temo de achar um jeito melhor de fazer isso, chamar funcao toda vez pra string statica nao faz sentido

2021-04-20 10:43 UTC, Yurickh commented
Tem algum motivo pra introduzir i18n nesse ponto do projeto, ou é pela experiência de fazer acontecer mesmo?

2021-04-20 13:13 UTC, Canato commented on src/translations/str.rs
> +fn intro() -> String {
procurei e não achei se tem objeto em rust que pode ser gerado. Olhei umas Libraries pra isso, mas nenhuma parecia boa na real

2021-04-20 13:13 UTC, Canato commented
> Tem algum motivo pra introduzir i18n nesse ponto do projeto, ou é pela experiência de fazer acontecer mesmo?

Experiencia pra tocar em rust / ter o que fazer

E poder ter o Bot em inglês pro repo e PT pra usarmos

2021-04-20 13:18 UTC, sousandrei commented on src/translations/str.rs
> +fn intro() -> String {
ve o comment acima, a gente simplesmente usa string slice de constantes e so compila pro certo
```rust
const INTRO: &str = "alguma coisa"
```

2021-04-21 07:08 UTC, Canato commented
Deu preguiça, talvez continue depois

2021-04-21 07:08 UTC, closed without merging